### ISSUE TITLE
Supervise by normal maps

### ISSUE THREAD

**Issue by yd-yin** [lioryariv/idr#13]
Hi, thanks for the great work!

I wonder if this differentiable renderer is suitable to supervise the SDF by normal maps.
Since computing normals would implement another gradient computation, is there any trouble with this?

Thanks!

**Comment by lioryariv** [comment]
Hi :)
Note that the normal information per pixel is already computed (used as input to the renderer network), so it seems to be quite straightforward to incorporate it with normal maps supervision.
