### ISSUE TITLE
Images preprocessing

### ISSUE THREAD

**Issue by ThibautLbl** [lioryariv/idr#15]
In the data_convention.md file, the preprocess script says that it generates the needed cameras.npz file. 
The code loads an initial cameras.npz file, but how should we build this cameras.npz file to run the preprocess code on new images ?

**Comment by ykasten** [comment]
The code generates the needed cameras.npz file which contains both the camera parameters and the normalization matrices. However,  it needs the camera matrices as an input which are stored in the input cameras.npz file in this example. 

In more details, the input cameras.npz file contains the camera matrices, where P_i = cameras['world_mat_%d' % i][:3, :] is a 3x4 matrix that projects points from the 3D world coordinates to the 2D coordinates of image i (intrinsics and extrinsics, i.e. P=K[R | t] ) 

The output cameras.npz contains also a normalization matrix for changing the coordinates system such that the captured object is located inside the unit sphere.

**Comment by qinzhibao123** [comment]
How do you get the input cameras.npz (world_mat and scale_mat), not the output cameras_new.npz?
