### ISSUE TITLE
why not Normalize the normal which input to the rendering network?

### ISSUE THREAD

**Issue by iYuqinL** [lioryariv/idr#17]
In the code: https://github.com/lioryariv/idr/blob/44959e7aac267775e63552d8aac6c2e9f2918cca/code/model/implicit_differentiable_renderer.py#L249
I found that the normal predicted by the implicit network is directly input to the rendering network without normalization. 

I want to know if it is well-designed by you, and why?

**Comment by lioryariv** [comment]
Hi,
Yes, it is well-design.
Note that since we enforcing the Eikonal regularization term over the implicit network (equation 11 in the paper), we have (approximately) norm 1 gradient.

Best
Lior

**Comment by iYuqinL** [comment]
Oh, I got it.

Thank you very much.
