### ISSUE TITLE
Will the batch size affect the result?

### ISSUE THREAD

**Issue by lintian-a** [lioryariv/idr#21]
Hi I noticed that the default batch size is 1 and I was thinking that increasing the batch size would speed up the training. But After I set the batch size to 25. The result looks blury comparing to the result trained with batch size one. I am wandering what might go wrong in my setting. Have you met such an issue before?

**Comment by lioryariv** [comment]
We found that working with a batch size of 1 yield the best results. We attribute that to the stochastic manner of the optimization process.
