### ISSUE TITLE
Variable light sources

### ISSUE THREAD

**Issue by GasparPizarro** [lioryariv/idr#24]
In the paper, the surface light field assumes, to my understanding, that the light source is fixed in the scene, and the DTU MVS dataset uses fixed lights, so, would moving light sources (like a light attached to the camera) worsen the performance of the method?

On a similar topic, what effect would including images with the same camera poses but different lighting conditions (position or intensity) have on the quality of the 3d reconstructions?

**Comment by lioryariv** [comment]
Our method assumes fixed lighting settings for the scene reconstruction.

However, you can train scenes independently with different lighting, for example, running separately on the 7 different lighting of DTU for the same scene, and try to see what happens in the disentanglement!

On a similar point, I suggest you check this interesting work - https://kai-46.github.io/PhySG-website/ - where they propose a relighting application with an IDR-based model.
