### ISSUE TITLE
How to plot the mesh of colmap?

### ISSUE THREAD

**Issue by JiaxiongQ** [lioryariv/idr#26]
Hi! Greak work!
I want to know how to save the mesh as an image like the photos in your paper.
Thanks!

**Comment by ahnaf1393** [comment]
@JiaxiongQ did you manage to find a solution?

**Comment by lioryariv** [comment]
Hi, 
You can either use ParaView of MeshLab for visualization of the meshes.
In ParaView you can export images as follows:
![image](https://user-images.githubusercontent.com/37273500/148911270-4efd413f-6906-4886-9a68-d087e6770a1c.png)
