### ISSUE TITLE
How to get scale matrix

### ISSUE THREAD

**Issue by yeong-dev** [lioryariv/idr#27]
Hello, I am a big fan of this project
I wonder how you get the scale matrix with DTU dataset.
If you don't mind, could you share the code which you use to get scale matrix?

I think I solved it
Thank you

**Comment by teachyourselfcoding** [comment]
Hey are you able to provide any help with regards to obtaining camera.npz file? I'm looking to run the code on my own dataset

**Comment by yeong-dev** [comment]
The author already opened code to create cameras.npz file. Read DATACONVENTION.md

**Comment by teachyourselfcoding** [comment]
preprocess_cameras.py seems to require a cameras.npz file as well, rather than generate one as mentioned in DATACONVENTION, am I doing something wrong here?

> For running the pre-process script to generate a cameras.npz file that contains the suitable normalization matrix:
