### ISSUE TITLE
Additional data in the cameras.npz files

### ISSUE THREAD

**Issue by ahnaf1393** [lioryariv/idr#28]
I noticed that the `cameras.npz` file provided for the DTU dataset has some additional matrices called "camera_mat_{i}". Are these the 3x3 calibration matrices K from P = K[R | t]? 

I tried to extract `K`, `R` and `t` from P (which are "world_mat_{i}") using opencv:
`K, R, t, _, _, _ = cv2.decomposeProjectionMatrix(P2)`

The `K` that I get from here does not match with the corresponding "camera_mat_{i}". Also the `t` values that I get are confusing to me. `t` has the shape (4, 1) and usually the 4th entry is always 1, but that is not happening here. 

UPDATE:
The 't' values were actually okay. I forgot to divide it by the 4th entry

**Comment by ewrfcas** [comment]
The same question. The camera_mat seems like an intrinsic?

**Comment by ykasten** [comment]
We use the same format as DVR for cameras.npz that contains this information but we don't use camera_mat_{i} in our code.
