### ISSUE TITLE
 Pytorch CPU version 

### ISSUE THREAD

**Issue by kaisark** [lioryariv/idr#3]
I see the Pytorch in the environment.yml file uses pytorch=1.2.0=py3.7_cuda10.0.130_cudnn7.6.2_0. 

Can the code run with Pytorch CPU version as well?

conda install -c pytorch pytorch-cpu

Thanks.

**Comment by lioryariv** [comment]
I am not sure since there is a need to change the code properly, cause its' assume cuda environment.
