### ISSUE TITLE
question about evaluation

### ISSUE THREAD

**Issue by l1346792580123** [lioryariv/idr#30]
thanks for sharing this great work! I have downloaded the ground truth 3d point clouds from DTU dataset. While the point clouds contain the table and some point clouds are not complete. How did you get the chamfer distance from your generated meshes and the ground truth point coluds?

**Comment by lioryariv** [comment]
Hi, we used the official MATLAB evaluation code, which can be found by the DTU authors here - https://roboimagedata.compute.dtu.dk/?page_id=36 (under SampleSet).
