### ISSUE TITLE
How to get an initial cameras.npz file？

### ISSUE THREAD

**Issue by qinzhibao123** [lioryariv/idr#38]
How do you get the input cameras.npz (world_mat and scale_mat), not the output cameras_new.npz?

**Comment by tomcat123a** [comment]
using COLMAP.

**Comment by Holmes-Alan** [comment]
@tomcat123a using COLMAP can only get cameras.bin. How do you get cameras.npz?

**Comment by lioryariv** [comment]
cameras.npz are just the format we use for out dataloader, you can see for example how it is being treated inside [scene_dataset.py](https://github.com/lioryariv/idr/blob/main/code/datasets/scene_dataset.py) or more in [DATA_CONVENTION.md](https://github.com/lioryariv/idr/blob/main/DATA_CONVENTION.md).

**Comment by lioryariv** [comment]
For scale_mat you can use the script given in [normalize_cameras.py](https://github.com/lioryariv/volsdf/blob/main/data/preprocess/normalize_cameras.py)

**Comment by songsenIng** [comment]
> [对于 scale_mat，您可以使用normalize_cameras.py](https://github.com/lioryariv/volsdf/blob/main/data/preprocess/normalize_cameras.py)中给出的脚本[](https://github.com/lioryariv/volsdf/blob/main/data/preprocess/normalize_cameras.py)

Hello, could you tell me how to get the cameras_linear_init.npz file? Looking forward to your reply.
