### ISSUE TITLE
dividing dot product get nan in the result

### ISSUE THREAD

**Issue by Jarvisss** [lioryariv/idr#39]
https://github.com/lioryariv/idr/blob/44959e7aac267775e63552d8aac6c2e9f2918cca/code/model/sample_network.py#L15

**Comment by Jarvisss** [comment]
can I add a epsilon like 1e-6 in the denominator? will this cause other errors? @lioryariv

**Comment by lioryariv** [comment]
You can add a tiny epsilon for stability, should not be a problem. I guess the chances that normals and view directions are exactly perpendicular are quite low, but better add some tiny epsilon as sanity.
