### ISSUE TITLE
Train the model with blender synthetic data

### ISSUE THREAD

**Issue by jingma-git** [lioryariv/idr#4]
Hi, I am trying to train network with synthetic dataset from blender and trying to figure out the exact meaning 'scale_mats, world_mats' in scene_dataset.py Line41. And I did download the original DTU dataset, it seems only provide the intrinsic and extrinsic camera parameters. I want to know how did you preprocess the data, is it possible to upload the 'data processing code' used in the paper?

**Comment by lioryariv** [comment]
Hi, 
First of all, we plan to publish the code for the preprocessing of the data soon.

In the meanwhile:
-world_mat represents the camera projection matrix, that is P=K[R t], mapping 3D points in the world to image points.

- scale_mat represents a scalar matrix, used if the object is not center at the world origin and not contained in the unit sphere.
Note that for S as scale_mat, S^{-1} represents the transformation in 3D world coordinates that transforms the visual hull of the masked object to be inside the unit sphere. Therefore: P_new=P@S.

I'm guessing that in the case of synthetic data, the object is centered at the origin so scale_mat is just the identity, or scalar*identity, if the object is not contained in the unit sphere.

Best,
Lior
