### ISSUE TITLE
GEOMETRY_ID and APPEARANCE_ID failed to get evaluated

### ISSUE THREAD

**Issue by RanjithKatta** [lioryariv/idr#7]
I did try to run the last instruction , where for GEOMETRY_ID , I have given the trained surface model with surface_world_coordinates.ply and same for appearance_id too, even I have changed those generated evals to code and then tried to run the code by specifying the location_path saying evals/dtu_trained_cameras/surface_world_coordinates.ply 

But nothing worked for me, can you be bit more clear about the instructions for the execution. 
Thank you

**Comment by lioryariv** [comment]
I have a bug in the README file. 
For the disentanglement experiment, the correct file to run is 'evaluation/eval_disentanglement.py', meaning running:

   python evaluation/eval_disentanglement.py --geometry_id GEOMETRY_ID --appearance_id APPEARANCE _ID

Where GEOMETRY_ID and APPEARANCE _ID are integers - the id's for the scans we want to evaluate as geometry and appearance, appropriately. For example:

  python evaluation/eval_disentanglement.py --geometry_id 65 --appearance_id 110

I will fix the README, thanks for noticing that!

**Comment by RanjithKatta** [comment]
Yeah I understood, can I know why you haven't annotated some of the scan like 65, 106 and 118 where you referred to Differentiable volumetric rendering: Learning implicit 3d representations without 3d supervision. May I know what was the IDR consideration for this?

**Comment by lioryariv** [comment]
Those three scans were already annotated but the authors of DVR("Differentiable volumetric rendering: Learning implicit 3d representations without 3d supervision"), so we could just use their masks annotations and annotate ourselves the rests.
