### ISSUE TITLE
Cameras Coordinate System

### ISSUE THREAD

**Issue by eram1205** [lioryariv/idr#9]
Hi there,

First of all congrats on the project and on the code. It's really neat 🔥 .

I'm trying to run the code with my own scene and, even though the losses are printed with kind of meaningful values, they do not decrease and the learnt scene doesn't resemble at all at what it should. I was wondering if the issue could be related to the coordinate system used.

My coordinate system is this way:
![](https://i.stack.imgur.com/c9A0N.png)
- Cameras look towards z.
- Usually, if the object is at the origin, cameras position are somewhere in -z.

Could it be you are assuming an OpenGL-like coordinate system and that it could be the reason it doesn't work?
![](https://i.stack.imgur.com/CeUAq.png)
- Here cameras look towards -z.
- Cameras are usually located around +z if the object is at the origin.

Any thoughts will be very welcome.

Thanks in advance!

**Comment by eram1205** [comment]
Just found out the problem was due to the images and masks sorting. Working like a charm 👍 !

**Comment by lioryariv** [comment]
Glad it worked out!

**Comment by kajalsanklecha** [comment]
Do we need masks for all the images to run the code?

**Comment by lioryariv** [comment]
Yes. 
As I mentioned here - https://github.com/lioryariv/idr/issues/10#issuecomment-752592505
